"""
LLM-as-Judge Evaluator (Differentiator #1)

After a cover letter is written, a SECOND LLM call evaluates it against
a rubric. This catches regressions like:
  - Letter is too generic
  - Forbidden phrases slipped through
  - JD keywords not mirrored
  - Length out of bounds

In production LLM systems, this pattern is called "LLM-as-judge" or
"reference-free evaluation" and is the standard way to measure quality
without human labels.

Usage:
    from src.agents.evaluator import evaluate_cover_letter
    score = evaluate_cover_letter(letter_text, jd, company)
    print(f"Quality: {score.overall_quality}/10")
"""
from pydantic import BaseModel, Field
from typing import Literal

from src.llm import call_llm_structured


# ── Schema ────────────────────────────────────────────────────────────────────

class CoverLetterEvaluation(BaseModel):
    """LLM-as-judge evaluation of a cover letter."""

    overall_quality: int = Field(ge=0, le=10, description="Overall quality 0-10")
    specificity_score: int = Field(ge=0, le=10, description="How specific to this job vs generic")
    jd_alignment_score: int = Field(ge=0, le=10, description="How well it mirrors JD language")
    voice_authenticity_score: int = Field(ge=0, le=10, description="How human/non-AI it sounds")
    structure_score: int = Field(ge=0, le=10, description="4-paragraph hook→proof→fit→close structure")

    detected_ai_isms: list[str] = Field(
        default_factory=list,
        description="Generic AI phrases detected (empty if clean)"
    )
    missing_jd_keywords: list[str] = Field(
        default_factory=list,
        description="JD keywords NOT mentioned in the letter"
    )
    strengths: list[str] = Field(
        min_length=1, max_length=4,
        description="What the letter does well"
    )
    weaknesses: list[str] = Field(
        default_factory=list,
        description="What could be improved"
    )

    recommendation: Literal["send_as_is", "revise_minor", "rewrite"] = Field(
        description="Action recommendation based on evaluation"
    )


# ── Evaluator ────────────────────────────────────────────────────────────────

EVALUATOR_PROMPT = """You are a senior technical recruiter scoring a cover letter for quality.

This is a META evaluation: a cover letter was generated by an AI for a specific job.
Your job is to grade that letter objectively against professional standards.

# THE JOB
Company: {company}
Title: {title}
JD excerpt: {jd_excerpt}

# THE COVER LETTER TO EVALUATE
{letter_text}

# YOUR RUBRIC (score each 0-10)

1. **Overall quality** — Would you forward this to a hiring manager?
2. **Specificity** — Does it talk about THIS job and THIS company, or could it be sent to any AI role?
3. **JD alignment** — Are the JD's actual keywords (RAG, agents, MCP, etc.) mirrored naturally?
4. **Voice authenticity** — Does this read like a human wrote it, or does it sound like AI output?
5. **Structure** — 4 paragraphs: hook → technical proof → company fit → confident close?

# ANTI-PATTERNS TO FLAG
Detect any of these and add them to detected_ai_isms:
- "I am writing to express my interest"
- "I am passionate about"
- "I am excited to apply"
- "I believe I would be a great fit"
- "Please find attached"
- "I look forward to hearing"
- "I have a strong background in"
- "As you can see from my resume"
- Generic openers without specificity
- Sycophantic praise of the company

# RECOMMENDATION
- send_as_is: quality >= 8, no AI-isms, structure clean
- revise_minor: quality 6-7, fixable issues
- rewrite: quality < 6, fundamental problems

Return as JSON matching the schema."""


def evaluate_cover_letter(
    letter_text: str,
    job_description: str,
    company: str,
    title: str,
) -> CoverLetterEvaluation:
    """
    Evaluate a cover letter against a rubric using LLM-as-judge.

    Args:
        letter_text: The cover letter to evaluate
        job_description: Original JD for context
        company: Company name
        title: Role title

    Returns:
        CoverLetterEvaluation with scores, detected issues, and recommendation
    """
    prompt = EVALUATOR_PROMPT.format(
        company=company or "Unknown",
        title=title or "Unknown role",
        jd_excerpt=(job_description or "")[:2000],
        letter_text=letter_text,
    )
    return call_llm_structured(prompt, CoverLetterEvaluation)


# ── Embedding-based quality check (no LLM call) ──────────────────────────────

def check_keyword_overlap(letter: str, jd: str) -> dict:
    """
    Fast heuristic: how many of the JD's distinctive terms appear in the letter?
    Doesn't require an LLM call.

    Returns:
        {
            "overlap_pct": 0.0-1.0,
            "matched_terms": [...],
            "missed_terms": [...]
        }
    """
    import re

    # Extract candidate keywords from JD (3+ char alphanumeric tokens)
    jd_words = set(re.findall(r"\b[A-Za-z][A-Za-z0-9+#-]{3,}\b", (jd or "").lower()))
    letter_words = set(re.findall(r"\b[A-Za-z][A-Za-z0-9+#-]{3,}\b", (letter or "").lower()))

    # Filter common stopwords
    STOPWORDS = {
        "this", "that", "with", "from", "have", "will", "your", "their", "what",
        "which", "where", "when", "would", "could", "should", "about", "into",
        "they", "them", "these", "those", "been", "being", "were", "are", "and",
        "the", "for", "you", "our", "out",
    }
    jd_words -= STOPWORDS
    letter_words -= STOPWORDS

    if not jd_words:
        return {"overlap_pct": 0.0, "matched_terms": [], "missed_terms": []}

    matched = jd_words & letter_words
    return {
        "overlap_pct": len(matched) / len(jd_words),
        "matched_terms": sorted(matched)[:15],
        "missed_terms": sorted(jd_words - letter_words)[:15],
    }